name: project
services:
  dev:
    image: "${COMPOSE_PROJECT_NAME}/${COMPOSE_PROJECT_NAME}:dev"
    hostname: '${COMPOSE_PROJECT_NAME}'
    container_name: '${COMPOSE_PROJECT_NAME}-dev'
    build:
      context: "./"
      network: "host"
      dockerfile: "./docker/dev.dockerfile"
      args:
        PROJECT: "${COMPOSE_PROJECT_NAME}"
        IMAGE_BASE: "debian"
        IMAGE_TAG: "bookworm-slim"
        USER_GROUPS: "dialout video"
        PIP_REQUIREMENTS: ""
        APT_DEPENDENCIES: ""
        MAMBA_PACKAGES: "python=3.12"
    volumes:
      - './:/home/${COMPOSE_PROJECT_NAME}/${COMPOSE_PROJECT_NAME}'
      - '/tmp/.X11-unix:/tmp/.X11-unix'
    environment:
      DISPLAY: '${DISPLAY:-vnc:0.0}'
    working_dir: '/home/${COMPOSE_PROJECT_NAME}/${COMPOSE_PROJECT_NAME}'
    tty: true
  vnc:
    image: "camera/${COMPOSE_PROJECT_NAME}:vnc"
    hostname: "${COMPOSE_PROJECT_NAME}-vnc"
    container_name: "${COMPOSE_PROJECT_NAME}-vnc"
    build:
      context: "./"
      dockerfile: "./docker/vnc.dockerfile"
      network: "host"
      args:
        VNC_PASSWORD: "${COMPOSE_PROJECT_NAME}"
    ports:
      - "127.0.0.1:8080-8099:8080"
      - "127.0.0.1:5900-5999:5900"
networks:
  default:
    name: "${COMPOSE_PROJECT_NAME}"
